### ISSUE TITLE
建议使用v-slot替代slot-scope属性

### ISSUE THREAD

**Issue by MrHanson** [laomao800/vue-listview#1]
在研究listview源码的时候，发现里面用到了已经废弃的slot-scope属性；从vue2.6.0开始，官方文档推荐使用v-slot替代slot-scope，而且我看到项目依赖的vue版本是2.6.4，建议修改

**Comment by laomao800** [comment]
:coffee: 下个子版本更新。 https://github.com/laomao800/vue-listview/commit/aa5ffebd05f5f5f0c63fb29990ea16a7d0d570f9
