### ISSUE TITLE
vue+typescript中使用该插件，filterButton中的click事件会有this指向问题

### ISSUE THREAD

**Issue by lawrence998** [laomao800/vue-listview#8]
vue+typescript中使用该插件，filterButton中的click事件会有this指向问题

**Comment by laomao800** [comment]
能否提供一下复现代码？

------

另外使用上与是否使用 ts 应无直接关系，若是指内部 this 未指向当前页面实例，则这个是正常表现，可参考文档 [Prop: filterButtons - click](https://laomao800.github.io/vue-listview/dev/prop-filter-buttons.html#click) 内的演示，单独绑定指向：

```js
[
  {
    text: 'Button1',
    click: () => {
      alert(this.filterButtons.length)
    }
  },
  {
    text: 'Button2',
    click() {
      alert(this.filterButtons.length)
    }.bind(this)
  }
]
```
